### ISSUE TITLE
createParser Error on ISO/OData abnf Files

### ISSUE THREAD

**Issue by matthew-valenti** [pachet/heket#4]
Thanks for publishing this great module! I'm getting an error on createParser when trying to parse these ISO approved OData abnf files. I've tried removing all comments from the abnf files and variety of other different things. Any help/guidance appreciated.

```
const Heket = require('heket');
let abnf_string = require('fs').readFileSync('./odata-v4.abnf').toString();
var parser = Heket.createParser(abnf_string);

"Error: Invalid value passed to createParser():"
```

1.
https://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt

2.
https://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/abnf/odata-aggregation-abnf.txt

**Comment by pachet** [comment]
Hello! Sorry for the stupendously belated response. This is due to the same comment-only line parsing issue as reported in https://github.com/pachet/heket/issues/3. It should be fixed in [v1.3.0](https://github.com/pachet/heket/commit/7ff69162bf758179c36ac032f638c7ed58341503)
